name: Big one
on: push
jobs:
  dfbdbd:
    runs-on: ubuntu-latest
    steps:
      - name: x1
        run: echo "gbgbsgbwegbv"
      - name: x2
        uses: actions/checkout@v4
      - name: x3
        run: echo "ai haga"
    
    